<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VpsSpecSeeder extends Seeder
{
    public function run(): void
    {
        $specs = [
            [
                'id' => 1,
                'name' => 'Student Basic',
                'category' => 'vps',
                'cpu' => 1,
                'ram' => 1,
                'disk' => 20,
                'bandwidth' => 30,
                'cost_price' => 60000,
                'sell_price' => 80000,
                'payment_url' => 'https://lynk.id/vexahostcloud/n4qjjoj28r07/checkout',
                'is_active' => true,
                'tagline' => 'Cocok untuk belajar Linux & portfolio web dasar',
                'target_audience' => 'Pelajar, pemula Linux',
                'features' => json_encode(['1 Core vCPU', '1 GB RAM', '20 GB NVMe', 'Root Access']),
                'solution' => 'Server hemat untuk kebutuhan dasar dan pembelajaran.',
                'badge' => 'Entry Level',
                'default_stack' => 'none',
            ],
            [
                'id' => 2,
                'name' => 'Standard',
                'category' => 'vps',
                'cpu' => 2,
                'ram' => 4,
                'disk' => 60,
                'bandwidth' => 30,
                'cost_price' => 90000,
                'sell_price' => 110000,
                'payment_url' => 'https://lynk.id/vexahostcloud/11mvv6loxplq/checkout',
                'is_active' => true,
                'tagline' => 'Pilihan ideal website bisnis, REST API, & bot 24 jam',
                'target_audience' => 'Developer, UKM',
                'features' => json_encode(['2 Core vCPU', '4 GB RAM', '60 GB NVMe', 'Root Access']),
                'solution' => 'Performa seimbang untuk backend dan website produksi.',
                'badge' => 'Terpopuler',
                'default_stack' => 'coolify',
            ],
            [
                'id' => 3,
                'name' => 'Premium',
                'category' => 'vps',
                'cpu' => 2,
                'ram' => 8,
                'disk' => 100,
                'bandwidth' => 30,
                'cost_price' => 160000,
                'sell_price' => 210000,
                'payment_url' => 'https://lynk.id/vexahostcloud/yvkggzrgrznn/checkout',
                'is_active' => true,
                'tagline' => 'Multi-aplikasi Docker & production klien beban tinggi',
                'target_audience' => 'Freelancer, agency',
                'features' => json_encode(['2 Core vCPU', '8 GB RAM', '100 GB NVMe', 'Root Access']),
                'solution' => 'Kapasitas RAM lega untuk multi-container Docker.',
                'badge' => 'High Memory',
                'default_stack' => 'coolify',
            ],
            [
                'id' => 4,
                'name' => 'Startup',
                'category' => 'vps',
                'cpu' => 4,
                'ram' => 8,
                'disk' => 80,
                'bandwidth' => 100,
                'cost_price' => 280000,
                'sell_price' => 350000,
                'payment_url' => 'https://lynk.id/vexahostcloud/qy377kmr5qr6/checkout',
                'is_active' => true,
                'tagline' => 'Solusi tangguh 4 core untuk aplikasi startup & backend API',
                'target_audience' => 'Startup, software house',
                'features' => json_encode(['4 Core vCPU', '8 GB RAM', '80 GB NVMe', 'Root Access']),
                'solution' => 'Komputasi bertenaga untuk traffic bertumbuh.',
                'badge' => 'Scale Up',
                'default_stack' => 'coolify',
            ],
            [
                'id' => 5,
                'name' => 'Business',
                'category' => 'vps',
                'cpu' => 8,
                'ram' => 16,
                'disk' => 80,
                'bandwidth' => 100,
                'cost_price' => 480000,
                'sell_price' => 590000,
                'payment_url' => 'https://lynk.id/vexahostcloud/pmz005yex778/checkout',
                'is_active' => true,
                'tagline' => 'Resource 8 core masif untuk database besar & enterprise',
                'target_audience' => 'Enterprise, database berat',
                'features' => json_encode(['8 Core vCPU', '16 GB RAM', '80 GB NVMe', 'Root Access']),
                'solution' => 'Performa enterprise tanpa kompromi.',
                'badge' => 'Business Tier',
                'default_stack' => 'dokploy',
            ],
            [
                'id' => 6,
                'name' => 'Mahasiswa Basic',
                'category' => 'vps',
                'cpu' => 2,
                'ram' => 2,
                'disk' => 40,
                'bandwidth' => 30,
                'cost_price' => 70000,
                'sell_price' => 90000,
                'payment_url' => 'https://lynk.id/vexahostcloud/j7e559997k29/checkout',
                'is_active' => true,
                'tagline' => 'Resource 2 vCPU lega untuk praktikum, mini server & bot',
                'target_audience' => 'Mahasiswa IT, praktikum',
                'features' => json_encode(['2 Core vCPU', '2 GB RAM', '40 GB NVMe', 'Root Access']),
                'solution' => 'Paket khusus mahasiswa dengan harga bersahabat.',
                'badge' => 'Mahasiswa',
                'default_stack' => 'none',
            ],
            // VEXAHOST AI COMBO PACKAGES (Zero Setup • Siap Pakai dalam Hitungan Menit)
            [
                'id' => 7,
                'name' => 'Terminal Coding Agent',
                'category' => 'ai_combo',
                'cpu' => 2,
                'ram' => 4,
                'disk' => 60,
                'bandwidth' => 30,
                'cost_price' => 80000,
                'sell_price' => 115000,
                'payment_url' => 'https://lynk.id/vexahostcloud/674yy1kv815m/checkout',
                'is_active' => true,
                'tagline' => 'Ubah terminal VPS kamu jadi mesin coding otomatis bertenaga AI kelas dunia.',
                'target_audience' => 'Mahasiswa Teknik Informatika, backend developer, DevOps enthusiast.',
                'features' => json_encode([
                    'Claude Code CLI resmi dari Anthropic (siap pakai, tinggal tempel API key)',
                    'OpenCode CLI (alternatif multi-provider open-source)',
                    'Dev Essentials Pre-configured: Git, GitHub CLI (gh), Docker, Node.js LTS, Python 3.12, dan Zsh/Bash dengan autocomplete',
                    'Anti-Crash Swap Memory: Alokasi memori virtual otomatis agar compile kode berat tetap stabil',
                ]),
                'solution' => 'Customer tinggal SSH dari laptop apa pun, ketik claude atau opencode, dan biarkan AI menganalisis, merefaktor, serta membuatkan fitur kode secara mandiri.',
                'badge' => 'Terminal / SSH',
                'default_stack' => 'claude_opencode',
            ],
            [
                'id' => 8,
                'name' => 'Cloud AI Workstation',
                'category' => 'ai_combo',
                'cpu' => 2,
                'ram' => 6,
                'disk' => 80,
                'bandwidth' => 50,
                'cost_price' => 100000,
                'sell_price' => 150000,
                'payment_url' => 'https://lynk.id/vexahostcloud/28eqqvl88q48/checkout',
                'is_active' => true,
                'tagline' => 'Koding dengan asisten AI dari browser di mana saja — iPad, tablet, atau laptop kentang.',
                'target_audience' => 'Developer freelance, pelajar mobilitas tinggi, yang tidak ingin install software berat di laptop sendiri.',
                'features' => json_encode([
                    'Web VS Code Server (code-server): Editor VS Code lengkap yang bisa dibuka langsung lewat Google Chrome/browser dengan link HTTPS aman',
                    'Claude Code & OpenCode terpasang langsung di dalam Terminal VS Code browser',
                    'Ekstensi Populer Siap Pakai: Tailwind CSS IntelliSense, Prettier, Python, Docker, GitLens',
                    'Auto-Save & Background Runner: Pekerjaan tetap berjalan di cloud meski laptop kamu ditutup atau mati lampu',
                ]),
                'solution' => 'Solusi all-in-one tanpa perlu buka SSH atau terminal hitam. Buka browser, login, langsung ngoding ditemani AI Agent di terminal bawahnya.',
                'badge' => '⭐ Paling Populer / Best Value',
                'default_stack' => 'vscode_server',
            ],
            [
                'id' => 9,
                'name' => 'Hermes Autonomous Hub',
                'category' => 'ai_combo',
                'cpu' => 4,
                'ram' => 8,
                'disk' => 100,
                'bandwidth' => 100,
                'cost_price' => 130000,
                'sell_price' => 185000,
                'payment_url' => 'https://lynk.id/vexahostcloud/mqgmmo5gm24m/checkout',
                'is_active' => true,
                'tagline' => 'Server AI mandiri dengan multi-model routing & autonomous decision making.',
                'target_audience' => 'AI engineer, researcher, agency automation, pengguna ekosistem Hermes & Omniroute.',
                'features' => json_encode([
                    'Hermes Agent Runtime: Framework autonomous AI agent dengan tool eksekusi terminal, browsing, dan manipulasi data',
                    'OmniRoute / 9router Pre-installed: Proxy router cerdas untuk menggabungkan banyak provider AI (OpenAI, Claude, DeepSeek, OpenRouter) dengan fallback otomatis jika salah satu down',
                    'Web Management Dashboard: Pantau log eksekusi, prompt history, dan utilisasi token secara visual',
                ]),
                'solution' => 'Server yang bertindak sebagai "karyawan AI mandiri" yang bisa didelegasikan tugas tanpa perlu laptop pengguna terus menyala.',
                'badge' => 'Autonomous Hub',
                'default_stack' => 'hermes_agent',
            ],
            [
                'id' => 10,
                'name' => 'Enterprise Private AI & RAG',
                'category' => 'ai_combo',
                'cpu' => 4,
                'ram' => 16,
                'disk' => 120,
                'bandwidth' => 100,
                'cost_price' => 190000,
                'sell_price' => 265000,
                'payment_url' => 'https://lynk.id/vexahostcloud/znj5501mgq7g/checkout',
                'is_active' => true,
                'tagline' => 'Platform AI private lengkap: buat chatbot dokumen perusahaan tanpa data bocor ke pihak luar.',
                'target_audience' => 'Startup, UMKM, kantor konsultan, peneliti skripsi RAG/dokumen internal.',
                'features' => json_encode([
                    'Dify AI / Flowise Studio: Antarmuka visual (drag-and-drop) untuk membuat AI Workflow, Chatbot WhatsApp/Web, dan asisten pintar',
                    'Ollama Local Engine: Mesin eksekusi model lokal gratis tanpa biaya per-token (DeepSeek-R1 / Llama 3 / Qwen Coder)',
                    'Integrated Vector Database (Qdrant / Chroma): Penyimpanan memori dan indexing dokumen (PDF/Word/Excel) siap pakai',
                    'AnythingLLM Web Interface: Antarmuka obrolan dokumen mirip ChatGPT untuk tim kerja',
                ]),
                'solution' => 'Punya ChatGPT versi internal perusahaan sendiri yang aman, terisolasi, dan bisa membaca ribuan dokumen bisnis internal.',
                'badge' => 'Private AI & RAG',
                'default_stack' => 'dify_ollama',
            ],
            // VEXAHOST MANAGED DATABASE PACKAGES (Dedicated DB VPS)
            [
                'id' => 11,
                'name' => 'DB Micro',
                'category' => 'managed_db',
                'cpu' => 2,
                'ram' => 2,
                'disk' => 40,
                'bandwidth' => 20,
                'cost_price' => 60000,
                'sell_price' => 95000,
                'payment_url' => 'https://lynk.id/vexahostcloud/wdxjj1rm9104/checkout',
                'is_active' => true,
                'tagline' => 'Development, tugas kuliah, staging, web traffic rendah',
                'target_audience' => 'Menampung hingga ~50–80 Koneksi Bersamaan | Database aktif ~10–20 GB',
                'features' => json_encode([
                    'Kapasitas Beban: Menampung hingga ~50–80 Koneksi Bersamaan tanpa drop performa.',
                    'Volume Data: Optimal untuk database aktif hingga ~10–20 GB (jutaan baris data transaksi standar).',
                    'Respon Instan: Latensi lokal super cepat ~3–10 ms langsung dari Datacenter Jakarta.',
                    'Anti-Crash: Memory swap otomatis agar database tidak mati mendadak saat ada query berat.',
                    'Universal Connection: Siap ditembak langsung dari Vercel, Railway, VPS luar, DBeaver, atau TablePlus via IP Publik Static.',
                    'Auto-Backup: Skrip backup otomatis harian ke penyimpanan lokal aman.',
                    'Spesifikasi Mesin: 2 Core vCPU • 2 GB RAM DDR4 • 40 GB Enterprise NVMe • 20 Mbps (512 GB Bandwidth)',
                    'Pilihan Engine Siap Pakai: PostgreSQL 16 • MySQL 8.0 • MariaDB • Redis Cache',
                ]),
                'solution' => 'Database server terisolasi murni bebas gangguan web server dengan biaya ekonomis.',
                'badge' => 'Entry Level',
                'default_stack' => 'managed_database',
            ],
            [
                'id' => 12,
                'name' => 'DB Standard',
                'category' => 'managed_db',
                'cpu' => 2,
                'ram' => 4,
                'disk' => 60,
                'bandwidth' => 30,
                'cost_price' => 90000,
                'sell_price' => 145000,
                'payment_url' => 'https://lynk.id/vexahostcloud/4k4dd20v29yz/checkout',
                'is_active' => true,
                'tagline' => 'Production UMKM, SaaS early stage, e-commerce',
                'target_audience' => 'Kuat hingga ~200–350 Koneksi Bersamaan | Database aktif ~40–50 GB',
                'features' => json_encode([
                    'Kapasitas Beban: Kuat hingga ~200–350 Koneksi Bersamaan (Sanggup handle lonjakan pengunjung/flash sale).',
                    'Volume Data: Optimal untuk database aktif hingga ~40–50 GB dengan query & indeks cepat.',
                    'Dedicated Cache: Alokasi cache query 2.5 GB agar pembacaan data berulang terasa secepat kilat.',
                    '100% Beban Terisolasi: Web server kamu (PHP/Node.js) down atau error, database tetap aman & hidup 100%.',
                    'Connection Pooling Ready: Mengatur antrean koneksi otomatis saat aplikasi diserbu traffic tinggi.',
                    'Proteksi Penuh: Dedicated IP Publik Static + Skrip backup harian otomatis.',
                    'Spesifikasi Mesin: 2 Core vCPU • 4 GB RAM DDR4 • 60 GB Enterprise NVMe • 30 Mbps (1.54 TB Bandwidth)',
                    'Pilihan Engine Siap Pakai: PostgreSQL 16 • MySQL 8.0 • MariaDB • Redis • MongoDB 7',
                ]),
                'solution' => 'Performa database stabil untuk aplikasi produksi bisnis tanpa resiko kehabisan RAM.',
                'badge' => 'Terpopuler / Best Value',
                'default_stack' => 'managed_database',
            ],
            [
                'id' => 13,
                'name' => 'DB Enterprise / AI Vector',
                'category' => 'managed_db',
                'cpu' => 2,
                'ram' => 8,
                'disk' => 80,
                'bandwidth' => 30,
                'cost_price' => 150000,
                'sell_price' => 225000,
                'payment_url' => 'https://lynk.id/vexahostcloud/o15vv84gw7zz/checkout',
                'is_active' => true,
                'tagline' => 'High-traffic SQL, Vector Search (Qdrant/Chroma), RAG',
                'target_audience' => 'Sanggup menampung ~800–1.200+ Koneksi Bersamaan & AI Vector Search',
                'features' => json_encode([
                    'Kapasitas Beban: Sanggup menampung ~800–1.200+ Koneksi Bersamaan & pemrosesan query analitik kompleks.',
                    'AI Vector Search (<10ms): Siap untuk sistem RAG, asisten AI, dan chatbot dokumen perusahaan berkecepatan tinggi.',
                    'Volume Data: Dirancang untuk puluhan juta baris data (Big Data) atau jutaan embedding vektor dokumen.',
                    'Throughput Tertinggi: Bandwidth 30 Mbps dengan transfer data masif hingga 2.56 TB per bulan.',
                    'Toleransi Beban Ekstrem: Arsitektur memori lega menjamin stabilitas query join multi-tabel berat.',
                    'Enterprise Reliability: Dedicated IP Publik Static + Skrip backup otomatis harian.',
                    'Spesifikasi Mesin: 2 Core vCPU • 8 GB RAM High-Speed • 80 GB Enterprise NVMe • 30 Mbps (2.56 TB Bandwidth)',
                    'Pilihan Engine Siap Pakai: Qdrant • Chroma DB • PostgreSQL (pgvector) • MySQL Heavy • Redis Cluster',
                ]),
                'solution' => 'Database performa tinggi untuk beban traffic berat dan penyimpanan vector AI.',
                'badge' => 'Enterprise & AI Vector',
                'default_stack' => 'managed_database',
            ],
        ];

        foreach ($specs as $spec) {
            DB::table('vps_specs')->updateOrInsert(
                ['id' => $spec['id']],
                array_merge($spec, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
