@extends('layouts.admin', ['title' => 'Monitoring Operasional', 'headerTitle' => 'Monitoring Operasional', 'backUrl' => route('admin.index'), 'backLabel' => 'Kembali ke Dashboard Admin'])

@section('content')
<div class="space-y-6">
    <div class="flex items-center justify-between"><div><h2 class="text-lg font-bold text-slate-900">Health & Operasional</h2><p class="text-xs text-slate-500 mt-1">Pantau layanan bermasalah, provisioning yang macet, dan SLA helpdesk.</p></div><span class="text-xs text-slate-500">Diperbarui {{ now()->format('d M Y H:i') }}</span></div>
    <div class="grid grid-cols-2 md:grid-cols-5 gap-3">
        @foreach(['running' => 'Running', 'provisioning' => 'Provisioning', 'stopped' => 'Stopped', 'error' => 'Error', 'suspended' => 'Suspended'] as $key => $label)
            <div class="bg-white rounded-lg border border-slate-200 p-4"><span class="text-xs text-slate-500">{{ $label }}</span><p class="text-2xl font-bold mt-1 {{ $key === 'error' ? 'text-rose-600' : 'text-slate-900' }}">{{ $statusCounts[$key] ?? 0 }}</p></div>
        @endforeach
    </div>
    <div class="grid lg:grid-cols-2 gap-6">
        <div class="bg-white rounded-lg border border-slate-200 overflow-hidden"><div class="p-5 border-b border-slate-100 flex justify-between"><h3 class="font-bold text-slate-900">SLA Terlewat</h3><span class="text-xs text-rose-600 font-semibold">{{ $slaBreaches->count() }} tiket</span></div><div class="divide-y divide-slate-100">@forelse($slaBreaches as $ticket)<a href="{{ route('admin.tickets.show', $ticket->id) }}" class="block p-4 hover:bg-slate-50"><div class="flex justify-between gap-3"><span class="font-semibold text-sm text-slate-900">#TK-{{ str_pad($ticket->id, 4, '0', STR_PAD_LEFT) }} · {{ $ticket->subject }}</span><span class="text-xs text-rose-600 whitespace-nowrap">{{ $ticket->sla_due_at->diffForHumans() }}</span></div><p class="text-xs text-slate-500 mt-1">{{ $ticket->customer->full_name }} · {{ $ticket->assignee?->full_name ?? 'Belum ditugaskan' }}</p></a>@empty<div class="p-8 text-center text-xs text-slate-400">Tidak ada SLA yang terlewat.</div>@endforelse</div></div>
        <div class="bg-white rounded-lg border border-slate-200 overflow-hidden"><div class="p-5 border-b border-slate-100 flex justify-between"><h3 class="font-bold text-slate-900">Provisioning Macet (&gt;30 menit)</h3><span class="text-xs text-amber-600 font-semibold">{{ $staleProvisioning->count() }} VPS</span></div><div class="divide-y divide-slate-100">@forelse($staleProvisioning as $vps)<a href="{{ route('admin.instances') }}?search={{ urlencode($vps->hostname) }}" class="block p-4 hover:bg-slate-50"><div class="flex justify-between"><span class="font-semibold text-sm text-slate-900">{{ $vps->hostname ?? 'VPS-'.$vps->id }}</span><span class="text-xs text-amber-600">{{ $vps->created_at->diffForHumans() }}</span></div><p class="text-xs text-slate-500 mt-1">{{ $vps->customer->full_name ?? '-' }} · {{ $vps->public_ip ?? 'IP belum tersedia' }}</p></a>@empty<div class="p-8 text-center text-xs text-slate-400">Tidak ada provisioning yang macet.</div>@endforelse</div></div>
    </div>
    <div class="bg-white rounded-lg border border-slate-200 overflow-hidden"><div class="p-5 border-b border-slate-100"><h3 class="font-bold text-slate-900">Transisi Status Terbaru</h3></div><div class="overflow-x-auto"><table class="w-full text-left text-xs"><thead class="bg-slate-50 text-slate-500 uppercase"><tr><th class="px-5 py-3">Waktu</th><th class="px-5 py-3">VPS</th><th class="px-5 py-3">Transisi</th><th class="px-5 py-3">Alasan</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($recentTransitions as $row)<tr><td class="px-5 py-3 text-slate-500">{{ $row->created_at->format('d M H:i') }}</td><td class="px-5 py-3 font-semibold">{{ $row->vpsInstance->hostname ?? 'VPS-'.$row->vps_instance_id }}</td><td class="px-5 py-3"><span class="font-mono-code">{{ $row->from_status ?? '-' }}</span> → <span class="font-semibold">{{ $row->to_status }}</span></td><td class="px-5 py-3 text-slate-500">{{ $row->reason }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-400">Belum ada transisi.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
