@extends('layouts.dashboard', ['title' => 'Keamanan Akun', 'headerTitle' => 'Keamanan Akun'])

@section('content')
<div class="max-w-5xl space-y-6">
    <div><h2 class="text-xl font-bold">Keamanan & akses</h2><p class="text-sm text-slate-500 mt-1">Kelola autentikasi, session, API key, dan SSH key Anda.</p></div>
    <div class="grid lg:grid-cols-2 gap-6">
        <section class="bg-white border border-slate-200 rounded-xl p-6"><div class="flex items-start justify-between gap-4"><div><h3 class="font-bold">Two-factor authentication</h3><p class="text-sm text-slate-500 mt-1">Tambahkan lapisan keamanan saat login.</p></div><span class="text-xs font-bold px-2 py-1 rounded-full {{ $twoFactorEnabled ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700' }}">{{ $twoFactorEnabled ? 'Aktif' : 'Belum aktif' }}</span></div>
            <div class="mt-5 flex gap-2">@if($twoFactorEnabled)<form method="POST" action="{{ route('security.two-factor.disable') }}" class="flex gap-2">@csrf<input type="password" name="password" required placeholder="Password" class="w-32 rounded-lg border border-slate-300 px-3 py-2 text-sm"><button class="rounded-lg border border-rose-300 px-3 py-2 text-sm font-semibold text-rose-700">Nonaktifkan</button></form><a href="{{ route('security.recovery-codes') }}" class="rounded-lg border px-3 py-2 text-sm font-semibold">Recovery codes</a>@else<a href="{{ route('security.two-factor.enable') }}" class="rounded-lg bg-black px-3 py-2 text-sm font-semibold text-white">Aktifkan 2FA</a>@endif</div>
        </section>
        <section class="bg-white border border-slate-200 rounded-xl p-6"><h3 class="font-bold">Session & login activity</h3><p class="text-sm text-slate-500 mt-1">Periksa akses akun dan cabut perangkat yang tidak dikenal.</p><div class="mt-5 flex gap-2"><a href="{{ route('security.sessions') }}" class="rounded-lg border px-3 py-2 text-sm font-semibold">Kelola session</a><a href="{{ route('security.login-activity') }}" class="rounded-lg border px-3 py-2 text-sm font-semibold">Riwayat login</a></div></section>
    </div>
    <section class="bg-white border border-slate-200 rounded-xl p-6"><div class="flex items-center justify-between"><div><h3 class="font-bold">API keys</h3><p class="text-sm text-slate-500 mt-1">Token hanya ditampilkan satu kali setelah dibuat.</p></div></div>
        @if(session('api_key_plaintext'))<div class="mt-4 rounded-lg bg-amber-50 border border-amber-200 p-4"><p class="text-xs font-bold text-amber-800">Salin sekarang — token tidak bisa ditampilkan ulang</p><code class="block mt-2 break-all text-xs">{{ session('api_key_plaintext') }}</code></div>@endif
        <form method="POST" action="{{ route('security.api-keys.create') }}" class="mt-5 grid md:grid-cols-[1fr_1fr_auto] gap-2">@csrf<input name="name" required placeholder="Nama key, mis. CI production" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><input type="date" name="expires_at" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><button class="rounded-lg bg-black px-4 py-2 text-sm font-bold text-white">Buat API key</button></form>
        <div class="mt-5 divide-y">@forelse($apiKeys as $key)<div class="py-3 flex items-center justify-between gap-4"><div><p class="font-semibold text-sm">{{ $key->name }}</p><p class="text-xs text-slate-500">{{ $key->prefix }} · {{ $key->revoked_at ? 'Dicabut' : ($key->isExpired() ? 'Kadaluarsa' : 'Aktif') }}</p></div><div class="flex gap-2">@if(!$key->revoked_at)<form method="POST" action="{{ route('security.api-keys.rotate', $key->id) }}">@csrf<button class="text-xs font-semibold underline">Rotasi</button></form><form method="POST" action="{{ route('security.api-keys.revoke', $key->id) }}" data-confirm="Cabut API key {{ $key->name }}?"><button class="text-xs font-semibold text-rose-700 underline">Cabut</button></form>@endif</div></div>@empty<p class="py-4 text-sm text-slate-500">Belum ada API key.</p>@endforelse</div>
    </section>
    <section class="bg-white border border-slate-200 rounded-xl p-6"><h3 class="font-bold">SSH public keys</h3><p class="text-sm text-slate-500 mt-1">Gunakan SSH key agar tidak bergantung pada root password.</p><form method="POST" action="{{ route('security.ssh-keys.create') }}" class="mt-5 space-y-2">@csrf<div class="grid md:grid-cols-2 gap-2"><input name="name" required placeholder="Nama key" class="rounded-lg border border-slate-300 px-3 py-2 text-sm"><input name="public_key" required placeholder="ssh-ed25519 AAAA..." class="rounded-lg border border-slate-300 px-3 py-2 text-sm"></div><button class="rounded-lg bg-black px-4 py-2 text-sm font-bold text-white">Tambah SSH key</button></form><div class="mt-4 divide-y">@forelse($sshKeys as $key)<div class="py-3 flex justify-between"><div><p class="text-sm font-semibold">{{ $key->name }}</p><p class="text-xs text-slate-500 font-mono-code">{{ $key->fingerprint }}</p></div><form method="POST" action="{{ route('security.ssh-keys.delete', $key->id) }}" data-confirm="Hapus SSH key {{ $key->name }}?">@csrf @method('DELETE')<button class="text-xs text-rose-700 underline">Hapus</button></form></div>@empty<p class="py-4 text-sm text-slate-500">Belum ada SSH key.</p>@endforelse</div></section>
</div>
@endsection
